---
- hosts: all
  become: true  # Run most tasks with sudo privileges
  tasks:
    # Install Docker on macOS (without sudo)
    - name: Ensure Docker is installed on macOS
      when: ansible_os_family == "Darwin"
      homebrew:
        name: docker
        state: present
      become: false  # Do not escalate privileges for Homebrew

    # Install kubectl on macOS (without sudo)
    - name: Ensure kubectl is installed on macOS
      when: ansible_os_family == "Darwin"
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl
      become: false  # Do not escalate privileges for this task

    # Install Docker on Linux (requires sudo)
    - name: Ensure Docker is installed on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Install kubectl on Linux (requires sudo)
    - name: Ensure kubectl is installed on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    # Deploy the Kubernetes application
    - name: Deploy Kubernetes application
      command: kubectl apply -f data-analytics-app/k8s/deployment.yaml

    # Deploy the Kubernetes service
    - name: Deploy Kubernetes service
      command: kubectl apply -f data-analytics-app/k8s/service.yaml
